name: Build and Deploy

on:
  push:
    branches:
      - main
      - make_conda_env_mpi

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Conda  
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false

      - name: Create Conda Environment With MPI
        run: make create-conda-env-mpi
      
      - name: Test MPI
        run: |
          conda run -n website-redesign-mpi \
          mpiexec -np 2 nrniv -mpi -python -c '
          from neuron import h;
          from mpi4py import MPI;
          print(f"Hello from proc {MPI.COMM_WORLD.Get_rank()}");
          h.quit()'

      - name: Modify .gitignore
        run: |
          # Remove the line that ignores HTML files in the content directory
          grep -v '^content/\*\*/\*.html$' .gitignore > .gitignore.tmp && mv .gitignore.tmp .gitignore
          cat .gitignore

      - name: Build Website
        run: conda run -n website-redesign-mpi env PYTHONUNBUFFERED=1 python build.py

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
