name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Conda  
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false

      - name: Create Conda Environment
        run: make create-conda-env-mpi

      - name: Modify .gitignore
        run: |
          # Remove the line that ignores HTML files in the content directory
          grep -v '^content/\*\*/\*.html$' .gitignore > .gitignore.tmp && mv .gitignore.tmp .gitignore
          cat .gitignore

      - name: Build Website
        run: conda run -n website-redesign-mpi python build.py

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
